#!/usr/bin/env bash
# Bash script that manages manage_my_process

my_file="manage_my_process"
pid_file="/var/run/my_process.pid"

if [ "$#" -eq 1 ]; then
	if [ "$1" == "start" ]; then
		./$my_file &
		echo "$!" >> $pid_file
		echo "manage_my_process started"
	elif [ "$1" == "stop" ]; then
		kill "$(cat $pid_file)"
	        rm $pid_file
		echo "manage_my_process stopped"
	elif [ "$1" == "restart" ]; then
		kill "$(cat $pid_file)"
		rm $pid_file
		./$my_file &
		echo "$!" >> $pid_file
		echo "manage_my_process restarted"
	fi
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
