#!/usr/bin/env bash
# Bash script that manages manage_my_process

case "$1" in
	start)
		manage_my_process &
		echo "manage_my_process started"
		echo "$!" > /var/run/my_process.pid
		;;
	stop)
		kill "$(cat /var/run/my_process.pid)"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		stop
		start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
