#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd

filename="/etc/passwd"

while IFS=: read -r username _ userid _ _ home _
do
    echo "$username:$userid:$home"
done < "$filename"
