#!/usr/bin/env bash
# Bash script that configures an ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.old

echo "127.0.0.2 localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
